services:
  - type: web
    name: autism-detection-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: '' # To be filled in the Render dashboard (Supabase URL)
      - key: SUPABASE_ANON_KEY
        value: '' # To be filled in the Render dashboard (Supabase Anon Key)
