services:
  - type: web
    name: autism-detection-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: 'https://ewwcnhibkxjonyvotwds.supabase.co'
      - key: SUPABASE_ANON_KEY
        value: 'sb_publishable_lJPGe5YFMG5mzD3HFv8IPQ_Jxsx8rUz'
